### ISSUE TITLE
Setting stack on WLError causes infinite loop

### ISSUE THREAD

**Issue by t3rminus** [balderdashy/waterline#1001]
Seems to have been introduced with the recent fix for this issue: https://github.com/balderdashy/waterline/issues/913

WLError.stack is set to itself in the setter, causing an infinite loop
```javascript
Object.defineProperties(WLError.prototype, {
  stack: {
    enumerable: true,
    get: function () {
      return util.format('Error (%s) :: %s\n%s', this.code, this.reason, this.rawStack);
    },
    set: function (value) {
      this.stack = value; // Infinite loop?
    }
  }
/// Snip
});
```

When I cause a WLValidationError, the server crashes with this error:
```
sails/node_modules/waterline/lib/waterline/error/WLError.js:129
verbose:     set: function (value) {
                  ^
verbose: RangeError: Maximum call stack size exceeded
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:129:19)
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:130:18)
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:130:18)
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:130:18)
(... snip about 50x more ...)
```

**Comment by dmarcelino** [comment]
@t3rminus, |I take it you're referring to the changes in [PR #920](https://github.com/balderdashy/waterline/pull/920/files#diff-8529b4b9f350440863f04bae69842609R123)?

@tjwebb, can you comment?

**Comment by eddieajau** [comment]
I have run into this bug too. I accidentally passed an undefined variable to a `findOne` call on a collection (albeit in a Sails test harness).

**Comment by dmarcelino** [comment]
PR #1045 should fix this. @t3rminus, @eddieajau can you please try it?
