### ISSUE TITLE
TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by elennaro** [balderdashy/waterline#1087]
On model *Customer.js*:

````javascript
module.exports = {
	attributes: {
		name: { type: 'string', required: true, size: 100 },
		phone: { type: 'string', unique: true, required: true, size: 15 },
		//Relations
		orders: { collection: 'order', via: 'customer' }
	},
	setPhonePrefix: function setPhonePrefix(values, prefix) {
		var regexp = new RegExp('^\\' + (prefix || "+995") + '.*$');
		values.phone && !regexp.test(values.phone)
						&& (values.phone = "+995" + values.phone);
		return values;
	},
	beforeCreate: function(values, cb) {
		this.setPhonePrefix(values);
		cb();
	},
	beforeUpdate: function(values, cb) {
		this.setPhonePrefix(values);
		cb();
	},
	beforeFind: function(query, cb) {
		this.setPhonePrefix(query);
		cb();
	}
};
````

On test:

````javascript
/* global describe, Customer */
var chai = require('chai'),
	assert = chai.assert,
	searchCriteria = { phone: '555555555' },
	customerToCreate = { name: 'san', phone: '555555555' };

before(function (done) {
	Customer.destroy({ }, function (err) {
		done(err);
	});
});

after(function (done) {
	Customer.destroy({ }, function (err) {
		done(err);
	});
});

describe('Customer', function () {

	it('#findOrCreate()', function (done) {
		Customer.setPhonePrefix(searchCriteria);
		Customer.findOrCreate({ where: searchCriteria }, customerToCreate)
			.then(function (foundOrCreated) {
				assert.propertyVal(foundOrCreated, 'name', "san", "Name of customer");
				assert.propertyVal(foundOrCreated, 'phone', "+995555555555", "Phone of customer");
				Customer.find({ where: searchCriteria })
						.then(function (result) {
							assert.equal(result.length, 1);
							var customer = result[0];
							assert.propertyVal(customer, 'name', "san", "Name of customer");
							assert.propertyVal(customer, 'phone', "+995555555555", "Phone of customer");
							done();
						})
						.catch(done);
				}).catch(done);
	});

});
````

**Comment by devinivy** [comment]
I don't know how you're running your tests, but I don't have any reason to believe that `Customer` should exist at that point.  Maybe you're using sails and are used to models being made globals.

**Comment by particlebanana** [comment]
Yup, seems `Customer` isn't being correctly set as a global.

**Comment by elennaro** [comment]
Well It actually is set as global correctly. Because the error happens for line 14.
Sorry that I didn't mention before: my test environment is initialized as required, i thought it's obviously that I must recheck all other possibilities before creating the issue here.
An here is the initialization of my tests (there is another dozen of them that works perfectly) - bootstrap.test.js:

````javascript
var Sails = require('sails'),
				mocha = require('mocha'),
				tk = require('timekeeper'),
				sails;

var time = new Date('2015-05-15T01:01:01');
tk.freeze(time);

before(function (done) {
	Sails.lift({
		models: {
			connection: 'localDiskDb',
			migrate: 'drop'
		}
	}, function (err, server) {
		sails = server;
		sails.log.verbose("Sails loaded?", err, server);
		if (err) return done(err);
		done(err, sails);
	});
});

after(function (done) {
	// here you can clear fixtures, etc.
	sails.lower(done);
});
````

**Comment by elennaro** [comment]
Can we kindly reopen/review this issue?

**Comment by devinivy** [comment]
Perhaps sails are being lowered before your `after` test callback is running.  I don't think waterline is unsetting your global `Customers` variable, or setting it to `undefined`.  Mind logging at the beginnig of all four `before` and `after` callbacks to determine the order in which they're run?

**Comment by elennaro** [comment]
Thanks, @devinivy.
You are right.
Here's log:
````bash
bootstrap.test before Sails.lift callback
Customer.test before
Customer.test before destroy callback
ok 1 OrderController #createOrder()
Customer.test #findOrCreate()
Customer.test #findOrCreate() callback
Customer.test #findOrCreate() find callback
//Other tests ommited
bootstrap.test after
bootstrap.test after sails.lower callback undefined [ undefined, undefined, undefined ]
Customer.test after
not ok 25  "after all" hook
  TypeError: Cannot read property 'destroy' of undefined
      at Context.<anonymous> (D:\System\Dropbox\in2circle\Development_I2C\sadili.ge\test\unit\models\Customer.test.js:17:11)
      at Context.<anonymous> (D:\System\Dropbox\in2circle\Development_I2C\sadili.ge\test\unit\controllers\OrderController.test.js:38:2)
      at D:\System\Dropbox\in2circle\Development_I2C\sadili.ge\test\bootstrap.test.js:43:3
      at net.js:1419:10
````

**Comment by devinivy** [comment]
I don't think there are any changes we can make in waterline to help you out here– you may be better off opening an issue in the sails repo, since it seems to have to do with the order of operations with sails test bootstrapping.  What do you think?  Good luck!

**Comment by elennaro** [comment]
Thanks. Sails is OK too.
So thanks for your time.
I think I should close it now.
