### ISSUE TITLE
ConnectionError: Connection is closed.

### ISSUE THREAD

**Issue by bing6** [balderdashy/waterline#1202]
```
me.models.users.find().exec(function (err, data) {
     console.log(err);
});
me.models.accounts.find().exec(function (err, data) {
    console.log(err);
});

```

result

```
Error (E_UNKNOWN) :: Encountered an unexpected error
ConnectionError: Connection is closed.
    at /Users/bing/NodeJS/UserServiceApp/src/UserServiceAppProject/node_modules/waterline-sqlserver/node_modules/mssql/lib/main.js:1492:17
    at process._tickCallback (node.js:355:11)

Details:  ConnectionError: Connection is closed.

null
```

What should I do..

**Comment by devinivy** [comment]
What is your connection configuration?  Does this happen consistently?

**Comment by particlebanana** [comment]
Sounds like there isn't a pooling option set or something on the `sql-server` adapter. Probably best to ask in that repo.
