### ISSUE TITLE
crashes when trying to update a model with a new association-record-to-create

### ISSUE THREAD

**Issue by mkeremguc** [balderdashy/waterline#533]
title is self explanatory i believe.. here is the error i get:
```
/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:532
    this.create(record).exec(function(err, val) {
         ^
TypeError: Object #<Object> has no method 'create'
    at createRecord (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:532:10)
    at createRunner (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:521:20)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:124:9)
    at mapAssociations (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:524:11)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:46:24)
```

**Comment by paquettea** [comment]
Thanks for sharing you investigation in details. I encountered the same issue, and the fix you are suggesting seems to be properly working ... I hope we will have a followup on this soon.

**Comment by cratervale** [comment]
Bump

**Comment by mkeremguc** [comment]
bump

**Comment by mkeremguc** [comment]
can you PR already ?

**Comment by paquettea** [comment]
https://github.com/balderdashy/waterline/pull/850

**Comment by tjwebb** [comment]
> can you PR already ?

If you're too lazy to submit your own patch, you're not allowed to complain.

**Comment by mkeremguc** [comment]
@tjwebb paquettea already committed my suggestion on his own repo so what is wrong here to ask him to PR ? moreover, i'm not complaining

**Comment by devinivy** [comment]
See #934 .
