### ISSUE TITLE
nestedOperations update Problem. 

### ISSUE THREAD

**Issue by geilt** [balderdashy/waterline#644]
Using the following attributes and passing in an array of mongoids. Trying like hell to store mongo ids in an array.

investors: {
   model: 'User',
   type: 'array'
},

/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:532
    this.create(record).exec(function(err, val) {
         ^
TypeError: Object #<Object> has no method 'create'
    at createRecord (/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:532:10)
    at createRunner (/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:521:20)
    at /node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:124:9)
    at mapAssociations (/node_modules/sails/node_modules/waterline/lib/waterline/utils/nestedOperations/update.js:524:11)
    at /node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:46:24)

**Comment by devinivy** [comment]
Does this issue remain?

**Comment by mkeremguc** [comment]
yes. https://github.com/balderdashy/waterline/issues/533

**Comment by dmarcelino** [comment]
Hi @mkeremguc, there have been two PRs (#889 and #898) recently released that address nested updates. Can you try the latest version of waterline and check if the issue remains? Thanks

**Comment by mkeremguc** [comment]
Hi @dmarcelino, unfortunately the issue still remains on latest waterline(0.10.20). can you please check my observation and possible fix within #533 ?

**Comment by mkeremguc** [comment]
obviously this: https://github.com/balderdashy/waterline/issues/533#issuecomment-68079748

**Comment by dmarcelino** [comment]
@mkeremguc, thanks for checking. The PRs I mentioned fixed several issues with nested updates and I wanted to be sure that it didn't fix this issue.

I've left a comment on PR #850 which is supposedly the fix for this issue.

**Comment by mkeremguc** [comment]
PR #930

**Comment by dmarcelino** [comment]
Fixed via PR #930. If the latest master version doesn't fix this, please reopen.
