### ISSUE TITLE
Frequent DB Connection timeout

### ISSUE THREAD

**Issue by yomexzo** [balderdashy/waterline#773]
I have been having issues with my sails app deployment. I often get the following stack trace saying sails-mysql / waterline experiences a timeout while trying to spawn a new connection. But in every case, the DB is always up and running as I can connect to it using mysql clients. It happens often but haven't been able to determine it's pattern or what triggers it.

	Error: connect ETIMEDOUT
	    at afterwards (/sites/smser/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
	    at /sites/smser/node_modules/sails-mysql/lib/connections/spawn.js:40:7
	    at Pool.<anonymous> (/sites/smser/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:47:16)
	    at Handshake.Sequence.end (/sites/smser/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
	    at Protocol.handleNetworkError (/sites/smser/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:282:14)
	    at PoolConnection.Connection._handleNetworkError (/sites/smser/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:303:18)
	    at PoolConnection.Connection._handleConnectTimeout (/sites/smser/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:299:8)
	    at Socket.g (events.js:180:16)
	    at Socket.emit (events.js:92:17)
	    at Socket._onTimeout (net.js:327:8)
	Details:  Error: Could not connect to MySQL:
	Error: connect ETIMEDOUT

**Comment by randallmeeker** [comment]
getting the same thing on mongo

**Comment by mlagace** [comment]
Same thing here, getting a lot of timeouts

**Comment by Josebaseba** [comment]
I've the same issue. It happens some times with no a clear pattern.

**Comment by Josebaseba** [comment]
Maybe changing the timeout connection limit will fix this issue:

http://blog.mongolab.com/2013/10/do-you-want-a-timeout/

**Comment by devinivy** [comment]
Anyone have any leads here?  Any method of reproducing the issue at hand?

**Comment by Josebaseba** [comment]
For sails-mongo adapter this is the solution: https://github.com/balderdashy/sails-mongo/issues/246

**Comment by dmarcelino** [comment]
I believe this is a sails-mysql issue and should probably be discussed in balderdashy/sails-mysql#175.

**Comment by dmarcelino** [comment]
Regarding sails-mongo, this should have been fixed in balderdashy/sails-mongo#277. Anyway this doesn't look like a waterline core issue, closing this for now.
