### ISSUE TITLE
[CRITICAL] Data corruption

### ISSUE THREAD

**Issue by Dallas62** [balderdashy/waterline#877]
Hi!

When i'm using Sails with sails-mysql, I have some data corruption on "High" frequency update...

The first one is that we cannot change associations at the same time.
ex:
```
Model.findOne(1).exec(function(err, model){
model.pets.add( 1 );
model.save();
});
Model.findOne(1).exec(function(err, model){
model.pets.add( 2 );
model.save();
});
Model.findOne(1).exec(function(err, model){
model.pets.add( 3 );
model.save();
});

// Expected on Joining Table:
// 1 - 1
// 1 - 2
// 1 - 3

// Result on Joining Table:
// 1 - 1
// Or
// 1 - 2
// Or
// 1 - 3
// Or
// 1 - 1
// 1 - 2
// Or
// 1 - 1
// 1 - 3
// Or
// 1 - 2
// 1 - 3
// Or ...
```
This could be done by HTTP request, so it's critical

Same with update:
```
Model.update(1, { pets: [1] }).exec();
Model.update(3, { pets: [1] }).exec();
Model.update(4, { pets: [1] }).exec();
// Expected on Joining Table:
// 1 - 1
// 3 - 1
// 4 - 1

// Result on Joining Table:
// 1 - 1
// 1 - 1
// 1 - 1
// Or
// 3 - 1
// 3 - 1
// 3 - 1
// Or
// 4 - 1
// 4 - 1
// 4 - 1
// Or
// 1 - 1
// 3 - 1
// 4 - 1
// Or
// 1 - 1
// 3 - 1
// Missing 4 - 1
// Or
// Missing 1 - 1
// 3 - 1 
// 4 - 1
// ...
// Math.random();
```
This could be done by HTTP request, so it's critical too

INFOS:
sails:           0.11.0
waterline:    0.10.18
sails-mysql  0.10.11

EDIT: On Many-To-Many

@mikermcneil @sgress454

**Comment by tjwebb** [comment]
You're not describing how your data was corrupted.

All of this stuff
> // 1 - 1
// 1 - 1
// 1 - 1

makes no sense to me

**Comment by particlebanana** [comment]
In the first example in a m:m it should never remove data from the join table. All it does is a create on the join table: https://github.com/balderdashy/waterline/blob/master/lib/waterline/model/lib/associationMethods/add.js#L323

In the second example it will remove associations for each model and then add pet 1. This is probably not what you want there!

**Comment by Dallas62** [comment]
@tjwebb `1 - 1` refer to Model { id: 1 } associate to Pet { id:1 }

@particlebanana The second example should associate the pet 1 to Model 1, 3 and 4, but create 3 associations on the same Model

**Comment by tjwebb** [comment]
> but create 3 associations on the same Model

Post your `Model` and `Pet` models. We need to see how your associations are defined. I still am not following what exactly it is that's happening, versus what you expect to happen.

**Comment by sgress454** [comment]
```
// 1 - 1
// 1 - 1
// 1 - 1
```

Is this what you're seeing in the join table in the database?  Three rows with model id 1 and pet id 1?

**Comment by Dallas62** [comment]
@sgress454 Exactly

**Comment by Dallas62** [comment]
```
// Pet
module.exports = {
    attributes: {
        owners: {
            collection: 'Owner',
            via: 'pets'
        }
    }
};
```

```
// Owner
module.exports = {
    attributes: {
        pets: {
            collection: 'Pet',
            via: 'owners',
            dominant: true
        }
    }
};
```

**Comment by tjwebb** [comment]
What versions of sails + waterline do you have installed?

**Comment by Dallas62** [comment]
@tjwebb 
```
INFOS:
sails: 0.11.0
waterline: 0.10.18
sails-mysql 0.10.11
```

**Comment by tjwebb** [comment]
I haven't used mysql in about 10 years, but I will test with the sails-postgres adapter. That will give me an idea whether this is waterline related, or adapter-specific.

**Comment by sgress454** [comment]
Thanks @tjwebb.  Nothing @Dallas62 is doing looks like it should cause a race condition, but depending on how the underlying code is implemented, who knows: might be a failure due to lack of transaction support.

**Comment by Dallas62** [comment]
@sgress454 Those bugs are really annoying, I can't implement features without hard tricks or trying to implements Queues on the server. And they happened over Socket.IO and HTTP...

**Comment by tjwebb** [comment]
@Dallas62 I understand, and I'll try to get to the bottom of this. On one hand it's surprising that no one else has run into this, but it's also possible that it's a recent regression.

**Comment by Dallas62** [comment]
I reproduce the bug with a test project (Without Sails).

Refer to: https://github.com/Dallas62/waterline-test-corruption

When you run this project you should have something like this (output):
```
Running test...
: before - start
: before - end
: run - start
:: Associate 9 with [ 9 ]
Error (E_UNKNOWN) :: Encountered an unexpected error
    at new WLError ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/lib/waterline/error/WLError.js:33:18)
    at duckType ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/lib/waterline/error/index.js:67:10)
    at errorify ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/lib/waterline/error/index.js:39:10)
    at wrappedCallback ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/lib/waterline/utils/normalize.js:320:15)
    at callback.error ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
    at [PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/lib/waterline/query/dql/update.js:213:23
    at taskCallback ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/async/lib/async.js:471:21)
    at [PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/waterline/lib/waterline/model/lib/defaultMethods/save.js:167:14
    at [PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/async/lib/async.js:454:17
    at [PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/async/lib/async.js:46:24)
    at Immediate.taskComplete ([PATH_TO_PROJECTS]/waterline-associations-corruption/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

Details:  [ { type: 'insert',
    collection: 'owner_pets__pet_owners',
    criteria: { pet_owners: 10, owner_pets: 10 },
    values: { pet_owners: 10, owner_pets: 10 },
    err: [Error: Trying to '.add()' an instance which already exists!] } ]

: run - end
The test is done.
```

**Comment by Dallas62** [comment]
@tjwebb @particlebanana @sgress454 ping

**Comment by devinivy** [comment]
@Dallas62 could you hook into the mysql module so that we can see what mySQL queries are being performed?  I'm just very curious if any deletes are occurring.  I was curious if #861 had anything to do with it.  You're experiencing the exact same issue when you pull in that PR?

**Comment by devinivy** [comment]
On the topic of race conditions, testing with sails-memory might be a good idea.  Since sails-memory has no i/o time, I would be interested to see if the issue does not occur using that adapter.

**Comment by Dallas62** [comment]
@devinivy actually there is no delete queries (depends on the method used)

But all insert in the joinning table are wrong (like an object not clone inside waterline) so of we join 1 with 1 and 2 with 2 at the same time, requests are (sometimes):
2 with 2 and 2 with 2.

Take a look at: https://github.com/Dallas62/waterline-test-corruption

**Comment by devinivy** [comment]
Results with both `sails-disk` and `sails-memory` look correct, but actually fail as @Dallas62 has described (ten instances of Owner 10 associated with Pet 10 rather than Owner x associated with Pet x for 1 < = x <=10)
```
Running test...
: before - start
: before - end
: run - start
:: Associate 1 with [ 1 ]
:: Associate 2 with [ 2 ]
:: Associate 3 with [ 3 ]
:: Associate 4 with [ 4 ]
:: Associate 5 with [ 5 ]
:: Associate 6 with [ 6 ]
:: Associate 7 with [ 7 ]
:: Associate 8 with [ 8 ]
:: Associate 9 with [ 9 ]
:: Associate 10 with [ 10 ]
: run - end
The test is done.
```

**Comment by devinivy** [comment]
There actually are `destroy`s occurring.  It _does_ have something to do with the `sync` that I removed in the PR referenced above.  However, in the PR I also broke this type of association update functionality, and that needs to be fixed.

Here's exactly what the adapter is doing (independent of adapter):
```
Update owner { where: { id: 1 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 2 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 3 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 4 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 5 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 6 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 7 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 8 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 9 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Update owner { where: { id: 10 } } set { updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT) }
Destroy owner_pets__pet_owners { where: { owner_pets: 1 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 2 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 3 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 4 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 5 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 6 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 7 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 8 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 9 } }
Destroy owner_pets__pet_owners { where: { owner_pets: 10 } }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Update owner { where: { id: 10 } } set { name: '6xguq189tgxqyrj46pora8sxi2rf088q',
  createdAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  updatedAt: Tue Mar 17 2015 15:35:54 GMT-0400 (EDT),
  id: 10 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Find pet { where: { id: 10 }, limit: 1 }
Find owner_pets__pet_owners { where: { pet_owners: 10, owner_pets: 10 }, limit: 1 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
Create owner_pets__pet_owners { pet_owners: 10, owner_pets: 10 }
```

**Comment by devinivy** [comment]
PR posted.

**Comment by Dallas62** [comment]
@devinivy Thanks dude, while take a look asap !

**Comment by Dallas62** [comment]
@sgress454 @particlebanana @tjwebb Can you check the PR #889 ?
I didn't had time yet, but its seems to be real bug that @devinivy fixed

**Comment by devinivy** [comment]
Given the high-priority nature of this bug, does someone mind looking at the PR? #889

**Comment by dmarcelino** [comment]
@devinivy, this is a part of the code I'm not yet familiar with... I would be more comfortable with this if there are was an automated test. Is it a hard scenario to test?

**Comment by Dallas62** [comment]
@dmarcelino You can reproduce it with https://github.com/Dallas62/waterline-test-corruption but I don't think you can easily implement a test in the PR

**Comment by devinivy** [comment]
I should be able to write a test for this.  I'll give it a whirl, at least!
