### ISSUE TITLE
.save(cb(err)) not having the callback called

### ISSUE THREAD

**Issue by cwoloszynski** [balderdashy/waterline#991]
I am using Sails (0.11.1) on node (0.10.33) with waterline (0.10.21).

I am in a controller and trying to update a password in a credential that I looked up, but the save() function is not calling the callback.  I am not sure what I've done wrong (I am new to node/javascript so this may be a newbie question).

The output is below.  All the console.log() calls generate output until the ones in the function for the save().

```
Attempting to complete account recovery process
Found user: {"userId":84,"emailAddress":"cwoloszynski@me.com","firstName":"charlie","lastName":"woloszynski","emailValidated":false,"id":84,"createdAt":"2015-01-27T15:15:10.823Z","updatedAt":"2015-01-27T15:15:10.823Z"}
found passport credential: {"user":84,"protocol":"local","password":"$2a$10$TqwzBEXCfq/qTe/4FWE6uel/Y3GP3Ee0jCkfXUZlDNr8FYckHh2p2","id":52,"createdAt":"2015-01-27T15:15:11.166Z","updatedAt":"2015-01-27T15:15:11.166Z"}
In Passport.credential.setPasswordViaRecoveryKey()
Setting password to: xxxxxxxxx
password set
done hashing:  err:null
credential after generation: {"user":84,"protocol":"local","password":"$2a$10$ZdH4jB68I87ObWlqbFnRDer.Gr4VcOMBUEzRey8mxafJh6oUpb3Su","id":52,"createdAt":"2015-01-27T15:15:11.166Z","updatedAt":"2015-01-27T15:15:11.166Z","resetPasswordToken":null}
after the validation step
exited out of passwordCredential.save() 
```

The code is below.    

Ideas?

```javascript
    completeRecovery: function(req, res) {
		console.log('Attempting to complete account recovery process');
	 
		var query = {emailAddress: req.body.username};
		
		User.findOne(query, function (err, user) {
			if (!user) {
				res.status(200).json({errorMsg: 'No user found'});
				return;
			}

			console.log('Found user: '+JSON.stringify(user));

			PassportCredential.findOne({ protocol : 'local', user : user.id }, function (err, passportCredential) {

				if (passportCredential == null) {
					res.status(200).json({errorMsg:'No credential found for this user'});
					return;
				}

				console.log('found passport credential: '+ JSON.stringify(passportCredential));
				
				passportCredential.setPasswordViaRecoveryKey(req.body.recoveryKey, req.body.password, function (err) {

					if (err) {
						console.log('error in validation key or password');
						res.status(200).json({errorMsg:'Invalid recovery key'}); 
						return;
					}
					console.log('credential after generation: '+JSON.stringify(passportCredential));
					passportCredential.validate(function(err) {
						if (err) {
							console.log('Error validating the new credential');
						}
						console.log('after the validation step');
						passportCredential.save(function(err, credential) { 
							console.log('Entering save callback');
							if (err) {
								console.log('Error saving updated password:'+err);
								res.status(200).json({errorMsg: 'Error saving updated password'});
								return;
							}
							console.log('saved new password in credential');
				
							res.status(200).json({username: req.body.username});
							return;
						});
					});
					
					console.log('exited out of passwordCredential.save()');

				});       
			});
		});
	}
```

**Comment by dmarcelino** [comment]
Interesting, to be honest I don't know if `.save()` can be used outside a many-to-many/hasMany associations scenario. If you check the [adapter tests](https://github.com/balderdashy/waterline-adapter-tests/search?p=1&q=save&utf8=✓) and the [docs](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#many-to-many-associations) those are the only scenarios covered.

Have you tried using the vanilla [`.update()`](https://github.com/balderdashy/waterline-docs/blob/master/query-methods.md#update-search-criteria--values--callback-)?

Out of curiosity, have you tried using a different adapter?

**Comment by cwoloszynski** [comment]
Good point about .save(). I converted the code to using .update() and I'm seeing a new error.  Perhaps I have something more fundamental wrong, as this model is also not indicating that it has the .update() function. 

```
Attempting to complete account recovery process
Found user: {"userId":84,"emailAddress":"cwoloszynski@me.com","firstName":"charlie","lastName":"woloszynski","emailValidated":false,"id":84,"createdAt":"2015-01-27T15:15:10.823Z","updatedAt":"2015-01-27T15:15:10.823Z"}
found passport credential: {"user":84,"protocol":"local","password":"$2a$10$TqwzBEXCfq/qTe/4FWE6uel/Y3GP3Ee0jCkfXUZlDNr8FYckHh2p2","id":52,"createdAt":"2015-01-27T15:15:11.166Z","updatedAt":"2015-01-27T15:15:11.166Z"}
In Passport.credential.setPasswordViaRecoveryKey()
Setting password to: winter999

/Users/charlie/hhmedia-w3/api/models/PassportCredential.js:122
						PassportCredential.update(this.id, {password: hash}, function (err){
						                   ^
TypeError: Object #<Object> has no method 'update'
    at /Users/charlie/hhmedia-w3/api/models/PassportCredential.js:122:26
    at /Users/charlie/hhmedia-w3/node_modules/bcryptjs/dist/bcrypt.js:1167:21
    at Object.next [as _onImmediate] (/Users/charlie/hhmedia-w3/node_modules/bcryptjs/dist/bcrypt.js:1047:21)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

The new code (in my data model and removed from my controller) is:
```javascript
		setPasswordViaRecoveryKey: function (recoveryKey, newPassword, next) {
			 console.log("In Passport.credential.setPasswordViaRecoveryKey()");
			if (this.resetPasswordToken === recoveryKey) {
					console.log('Setting password to: '+newPassword);
					bcrypt.hash(this.password, 10, function (err, hash) {
						if (err != null) {
							next(err);
							return;
						}
						this.resetPasswordToken = null;
						PassportCredential.update(this.id, {password: hash}, function (err){
							if (err) {
								next(err);
								return;
							}
							next(null, this);
						})			
					});
			} else {
				return next({errorMsg:'invalid recovery token'});
			}
		}
```

The data model is in 'api/models' in my Sails application.

**Comment by dmarcelino** [comment]
> The new code (in my data model and removed from my controller)

That doesn't sound like a good idea, something like an `Model.update()` should be on your controller. `api /models/` is meant for model definitions, validation code and maybe massaging some data but not much more.

**Comment by cwoloszynski** [comment]
I appreciate the feedback.  I am new to Sails and I was trying to keep the controller logic just about the REST interface and have a place for some middleware to support re-using the business logic.  I've moved the code back to the controller to follow your suggestion.

Using PasswordCredential.update() has the same symptom; the function is not called.  

The output now shows no log from the console.log('In Update').  Since the res.status(200) code is within that block, the HTTP connection hangs (as it has been for my other attempts).  

```
Attempting to complete account recovery process
Found user: {"userId":84,"emailAddress":"cwoloszynski@me.com","firstName":"charlie","lastName":"woloszynski","emailValidated":false,"id":84,"createdAt":"2015-01-27T15:15:10.823Z","updatedAt":"2015-01-27T15:15:10.823Z"}
found passport credential: {"user":84,"protocol":"local","password":"$2a$10$TqwzBEXCfq/qTe/4FWE6uel/Y3GP3Ee0jCkfXUZlDNr8FYckHh2p2","id":52,"createdAt":"2015-01-27T15:15:11.166Z","updatedAt":"2015-01-27T15:15:11.166Z"}
Hashing password
In bcrypt.hash
Calling update
```
The code in the controller is now:

```javascript
	completeRecovery: function(req, res) {
		console.log('Attempting to complete account recovery process');
	 
		var query = {emailAddress: req.body.username};
		
		User.findOne(query, function (err, user) {
			if (!user) {
				res.status(200).json({errorMsg: 'No user found'});
				return;
			}

			console.log('Found user: '+JSON.stringify(user));

			PassportCredential.findOne({ protocol : 'local', user : user.id }, function (err, passportCredential) {

				if (passportCredential == null) {
					res.status(200).json({errorMsg:'No credential found for this user'});
					return;
				}

				console.log('found passport credential: '+ JSON.stringify(passportCredential));

				if (passportCredential.resetPasswordToken != req.body.recoveryKey) {
					console.log('error in validation key or password');
					res.status(200).json({errorMsg:'Invalid recovery key'}); 
					return;
				}

				console.log('Hashing password');
				bcrypt.hash(req.body.password, 10, function (err, hash) {
					console.log('In bcrypt.hash');
					if (err != null) {
						console.log('Error in creating hash');
						next(err);
						return;
					}
					console.log('Calling update');
					PassportCredential.update(passportCredential.id, {password: hash}, function (err) {
						console.log('In update');
						if (err) {
							next(err);
							return;
						}
						passportCredential.resetPasswordToken = null;
						console.log('credential after generation: '+JSON.stringify(passportCredential));
						res.status(200).json({username: req.body.username});next(null, passportCredential);
					})			
					
				});       
			});
		});
	}
```
Any other thoughts?

Thanks in advance.

Charlie

**Comment by dmarcelino** [comment]
> I was trying to keep the controller logic just about the REST interface and have a place for some middleware to support re-using the business logic.

You can use some other file that is required by your controllers to do that, but avoid using CRUD operations in your model definitions.

> Using `PasswordCredential.update()` has the same symptom; the function is not called.

That is very weird... which adapter are you using? Have you tried using another adapter? Is your data-store busy somehow and hanging on the `.update()` operation?

**Comment by cwoloszynski** [comment]
I am using sails-disk (0.10.7).

In config/models.js, the connection is 'localDiskDb'.  

In config/connections.js, this connection points to adapter 'sails-disk'.

In .tmp, I see the file 'localDiskDb.db' and I have RW permission with it.  

I just dumped the database (set the migrate to 'drop') and restarted and the other code that creates a new user worked.  However, this part of the code is still hanging. 

I don't think that datastore is likely to hang on .update().

**Comment by cwoloszynski** [comment]
Thank you for helping me with this.  I found the issue. I had a beforeUpdate() in my model and it did not properly call next().

I sincerely apologize wasting your time.

**Comment by dmarcelino** [comment]
No worries, glad you managed you to figure out the issue.
